### ISSUE TITLE
flow is in OCaml :)

### ISSUE THREAD

**Issue by karelbilek** [RobinCsl/awesome-js-tooling-not-in-js#2]
Flow - an alternative to TypeScript (from Facebook) - is in OCaml.

I think it never really took off and got leapfrogged by TypeScript, because it's in OCaml, and nobody really knows OCaml (especially not FE developers), while TypeScript is just in TypeScript. 

But, it's not in JS :D so it could be on this list?

https://github.com/facebook/flow

**Comment by RobinCsl** [comment]
Hi Karel 👋 

Thanks for your contribution :)

It is already mentioned in the Linters (https://github.com/RobinCsl/awesome-js-tooling-not-in-js#linters) section, though I linked to the official website and not the GitHub repository. Do you have an opinion on what is more useful/preferred?

**Comment by karelbilek** [comment]
Ahh I missed it. Sorry
