### ISSUE TITLE
I'm building Volt - A Javascript Package Manager Written In Rust

### ISSUE THREAD

**Issue by XtremeDevX** [RobinCsl/awesome-js-tooling-not-in-js#25]
It would be awesome if you could add [volt](https://github.com/voltpkg/volt) to this list. Volt is a JavaScript package manager (it's still a WIP) written in Rust which is going to be a drop-in replacement for Yarn, NPM and PNPM. 

Here's a reddit post related to volt:
https://www.reddit.com/r/rust/comments/oymdoj/upcoming_volt_a_rustbased_package_manager_thats/

**Comment by RobinCsl** [comment]
Absolutely! Nice work! The benchmark looks promising! Will there be any plans to implement something like Yarn or npm workspaces?

I saw you forked the repo and added Volt in your fork, feel free to send a PR from it and I'll get it merged asap!
