### ISSUE TITLE
Tool proposals: Boa + Volta

### ISSUE THREAD

**Issue by slorber** [RobinCsl/awesome-js-tooling-not-in-js#9]
Hey, not sure if those tools belong here and in which section exactly but:
- https://github.com/boa-dev/boa
- https://volta.sh/

**Comment by RobinCsl** [comment]
Hey Sébastien,

Merci beaucoup :) These look cool!

I guess we could add a "JavaScript engines" section, with V8 in C++ and Boa in Rust.

Not sure about how to classify Volta though (which looks cool too!) "JavaScript Command-Line Tools Managers" sounds a bit verbose and maybe too specific as a section. 🤔 

Let me know if you'd like to open a PR or if I should handle it.

Thanks again!

**Comment by slorber** [comment]
No you can add those tools, I just send suggestions 😜

Also take a look at Hermes, a JS runtime for ReactNative

**Comment by RobinCsl** [comment]
I meant to create a PR and not merge to the main branch directly... 😅 

I just added your suggestions to the list!

Thanks again Sébastien!
